# Generated by Django 5.2.4 on 2025-12-06 02:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='badges/')),
                ('criteria', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('challenge_type', models.CharField(choices=[('find_errors', '7 Erros'), ('atendimento', 'Atendimento'), ('separacao', 'Separação')], max_length=20)),
                ('title', models.CharField(max_length=140)),
                ('prompt', models.TextField(blank=True)),
                ('difficulty', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('category', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2'), ('C3', 'C3'), ('C4', 'C4'), ('C5', 'C5')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity_type', models.CharField(choices=[('login', 'Login'), ('challenge_started', 'Desafio iniciado'), ('challenge_completed', 'Desafio concluído'), ('badge_earned', 'Badge conquistada'), ('level_up', 'Subiu de nível'), ('custom', 'Custom')], default='custom', max_length=32)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('details', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AtendimentoChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_scenario', models.TextField()),
                ('expected_response', models.TextField()),
                ('challenge', models.OneToOneField(limit_choices_to={'challenge_type': 'atendimento'}, on_delete=django.db.models.deletion.CASCADE, related_name='atendimento', to='api.challenge')),
            ],
        ),
        migrations.CreateModel(
            name='FindErrorsChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='challenges/find_errors/')),
                ('errors', models.JSONField(help_text='Lista de erros a serem encontrados.')),
                ('challenge', models.OneToOneField(limit_choices_to={'challenge_type': 'find_errors'}, on_delete=django.db.models.deletion.CASCADE, related_name='find_errors', to='api.challenge')),
            ],
        ),
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.PositiveIntegerField(help_text='Posição do ranking (1 = topo).')),
                ('score', models.PositiveIntegerField(default=0, help_text='XP total ou outro score.')),
                ('trend', models.CharField(choices=[('up', 'Subindo'), ('down', 'Descendo'), ('stable', 'Estável')], default='stable', help_text='Indica se o aluno subiu ou desceu recentemente.', max_length=6)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entry', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='LearningPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='Trilha personalizada', max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='learning_path', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PathModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=140)),
                ('challenge_type', models.CharField(choices=[('find_errors', '7 Erros'), ('atendimento', 'Atendimento'), ('separacao', 'Separação')], max_length=20)),
                ('position', models.PositiveIntegerField(default=1)),
                ('required_exercises', models.PositiveIntegerField(default=1, help_text='Quantidade de exercícios do módulo para marcar como concluído.')),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='api.learningpath')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('path', 'position')},
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('experience_points', models.PositiveIntegerField(default=0)),
                ('level', models.PositiveIntegerField(default=1)),
                ('streak', models.PositiveIntegerField(default=0, help_text='Dias seguidos ativos.')),
                ('badges', models.ManyToManyField(blank=True, related_name='profiles', to='api.badge')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SeparacaoChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge', models.OneToOneField(limit_choices_to={'challenge_type': 'separacao'}, on_delete=django.db.models.deletion.CASCADE, related_name='separacao', to='api.challenge')),
                ('medications', models.ManyToManyField(related_name='separacao_challenges', to='api.medication')),
            ],
        ),
        migrations.CreateModel(
            name='AssignedChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('in_progress', 'Em progresso'), ('completed', 'Concluído'), ('failed', 'Falhou')], default='pending', max_length=20)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_interaction_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_challenges', to=settings.AUTH_USER_MODEL)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='api.challenge')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='api.pathmodule')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'module', 'challenge')},
            },
        ),
        migrations.CreateModel(
            name='PathModuleChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.PositiveIntegerField(default=1)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_instances', to='api.challenge')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_challenges', to='api.pathmodule')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('module', 'challenge')},
            },
        ),
    ]
