from django.urls import path

from .views import (
    api_health,
    badges_list,
    challenges_list,
    current_session,
    sessions_list,
    revoke_session,
    leaderboard_view,
    learning_path_view,
    login_view,
    logout_view,
    me,
    profile_detail,
    register,
    activity_logs,
    separacao_exercises,
    separacao_submit,
    separacao_start,
    separacao_attempt_current,
    separacao_answer,
    atendimento_exercise,
    atendimento_submit,
    find_errors_start,
    find_errors_attempt,
    find_errors_submit,
    find_errors_image,
    medications_list,
    medications_import,
)

urlpatterns = [
    path("health/", api_health, name="api-health"),
    path("auth/register/", register, name="auth-register"),
    path("auth/login/", login_view, name="auth-login"),
    path("auth/logout/", logout_view, name="auth-logout"),
    path("auth/me/", me, name="auth-me"),
    path("auth/session/", current_session, name="auth-session"),
    path("auth/sessions/", sessions_list, name="auth-sessions"),
    path("auth/sessions/<int:session_id>/revoke/", revoke_session, name="auth-session-revoke"),
    path("profile/", profile_detail, name="profile-detail"),
    path("badges/", badges_list, name="badges-list"),
    path("leaderboard/", leaderboard_view, name="leaderboard"),
    path("learning-path/", learning_path_view, name="learning-path"),
    path("challenges/", challenges_list, name="challenges-list"),
    path("challenges/separacao/", separacao_exercises, name="separacao-exercises"),
    path("challenges/separacao/submit/", separacao_submit, name="separacao-submit"),
    path("challenges/separacao/start/", separacao_start, name="separacao-start"),
    path("challenges/separacao/attempt/", separacao_attempt_current, name="separacao-attempt-current"),
    path("challenges/separacao/attempt/<int:attempt_id>/answer/", separacao_answer, name="separacao-answer"),
    path("challenges/atendimento/", atendimento_exercise, name="atendimento-exercise"),
    path("challenges/atendimento/submit/", atendimento_submit, name="atendimento-submit"),
    path("challenges/find-errors/start/", find_errors_start, name="find-errors-start"),
    path("challenges/find-errors/attempt/<int:attempt_id>/", find_errors_attempt, name="find-errors-attempt"),
    path("challenges/find-errors/attempt/<int:attempt_id>/submit/", find_errors_submit, name="find-errors-submit"),
    path("challenges/find-errors/image/<path:image_path>/", find_errors_image, name="find-errors-image"),
    path("medications/", medications_list, name="medications-list"),
    path("medications/import/", medications_import, name="medications-import"),
    path("activity/", activity_logs, name="activity-logs"),
]
